name: Quarkiverse Pre Release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    name: pre release

    steps:
      - name: Check if PR is from a fork
        if: github.event.pull_request.head.repo.full_name != github.repository
        run: |
          echo '::error::Pre-release cannot be triggered from a fork.'
          exit 1

      - uses: radcortez/project-metadata-action@main
        name: retrieve project metadata
        id: metadata
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          metadata-file-path: '.github/project.yml'

      - name: Validate version
        if: contains(steps.metadata.outputs.current-version, 'SNAPSHOT')
        run: |
          echo '::error::Cannot release a SNAPSHOT version.'
          exit 1
      - name: Check if there are any pre-release error messages
        if: ${{ vars.PRE_RELEASE_ERROR != ''}}
        run: |
          echo '::error::${{ vars.PRE_RELEASE_ERROR }}'
          exit 1
